export const projects = [
  {
    title: "Django Todo App",
    description: "A clean and functional Django-based Todo app for managing tasks with user auth, CRUD operations, and responsive UI.",
    tech: ["Python", "Django", "HTML", "CSS", "SQLite"],
    live: "https://sarbeswarbhol.github.io/Todo-app/",
    code: "https://github.com/sarbeswarbhol/Todo-app",
  },
  {
    title: "Student Management System",
    description: "Django web app to manage students, guardians, classes, with photo upload and full CRUD support.",
    tech: ["Python", "Django", "HTML", "CSS", "Bootstrap", "SQLite"],
    live: "https://sarbeswarbhol.github.io/Student-Management/",
    code: "https://github.com/sarbeswarbhol/Student-Management",
  },
  {
    title: "ChatVerse",
    description: "Real-time chat and calling app with Django, WebSockets, and WebRTC for 1-on-1 and group communication.",
    tech: ["Python", "Django", "WebSockets", "JavaScript", "WebRTC"],
    live: "https://sarbeswarbhol.github.io/chatverse/",
    code: "https://github.com/sarbeswarbhol/chatverse",
  },
  {
    title: "BookMyShow Clone",
    description: "Full-stack movie ticket booking app with React frontend and Django backend — includes login, seat booking, and admin panel.",
    tech: ["React", "Django", "Tailwind CSS", "JavaScript", "Python"],
    live: "https://sarbeswarbhol.github.io/bookmyshow/",
    code: "https://github.com/sarbeswarbhol/bookmyshow",
  },
  {
    title: "MyFaceClone",
    description: "Facebook-style social networking clone in Django with auth, profiles, posts, and friends.",
    tech: ["Python", "Django", "HTML", "CSS", "Bootstrap", "SQLite"],
    live: "https://sarbeswarbhol.github.io/FaceClone/",
    code: "https://github.com/sarbeswarbhol/FaceClone",
  },
  {
    title: "Weather App",
    description: "React-based weather forecast app using live API for real-time data.",
    tech: ["React", "JavaScript", "HTML", "CSS", "API"],
    live: "https://sarbeswarbhol.github.io/weather/",
    code: "https://github.com/sarbeswarbhol/weather",
  },
  {
    title: "Recipe Finder",
    description: "JavaScript-based recipe search app using MealDB API with interactive recipe cards.",
    tech: ["HTML", "CSS", "JavaScript", "API"],
    live: "https://sarbeswarbhol.github.io/recipe-finder/",
    code: "https://github.com/sarbeswarbhol/recipe-finder",
  },
  {
    title: "Password Generator",
    description: "Responsive password generator with custom options and clipboard copy support.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://sarbeswarbhol.github.io/Password-Generator/",
    code: "https://github.com/sarbeswarbhol/Password-Generator",
  },
  {
    title: "Simple Calculator",
    description: "Web-based calculator built with HTML, CSS Grid, and JavaScript.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://sarbeswarbhol.github.io/Calculator/",
    code: "https://github.com/sarbeswarbhol/Calculator",
  },
  {
    title: "Stopwatch",
    description: "Millisecond-accurate stopwatch built with vanilla JavaScript and modern UI.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://sarbeswarbhol.github.io/Stopwatch/",
    code: "https://github.com/sarbeswarbhol/Stopwatch",
  },
];
